#! /usr/bin/python
import sys
import ConfigParser
from cs_control import CSControl

usage="""
cs_setsound

Usage: cs_setsound FILE

where FILE is a sound configuration file.
Format: see examples/patch1 included with the source.
"""

if(len(sys.argv)!=2):
    print(usage)
    sys.exit(1)


# Read settings file    
config=ConfigParser.RawConfigParser()
config.optionxform=str
config.read(sys.argv[1])


# init
channel=config.getint('main','channel')
cc=CSControl(channel-1) # MIDO numbers channels 0:15

# build sound parameter dictionary from config file
sound={}
for (controlname,value) in config.items('sound'):
    sound[controlname]=value

# Set sound generator parameters
cc.cswrite(sound)
del(cc)
